# Generated by Django 5.2.8 on 2025-11-12 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_client', models.CharField(choices=[('HEBERGEMENT', 'Hébergement'), ('CONFERENCE', 'Conférence'), ('INTERNE', 'Interne')], default='HEBERGEMENT', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_chambre', models.CharField(blank=True, max_length=20, null=True)),
                ('nom_evenement', models.CharField(blank=True, max_length=200, null=True)),
                ('date_arrivee', models.DateField(blank=True, null=True)),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('motif', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employe_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions_creees', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='assets.client')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='assets.departement')),
            ],
            options={
                'verbose_name': 'Attribution',
                'verbose_name_plural': 'Attributions',
                'ordering': ['-date_attribution'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='assets.departement'),
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='assets.departement')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
                'unique_together': {('nom', 'departement')},
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CHECK_OUT', 'Check-out'), ('CHECK_IN', 'Check-in'), ('MAINTENANCE', 'Maintenance'), ('MODIFICATION', 'Modification')], max_length=20)),
                ('etat_avant', models.CharField(blank=True, max_length=50, null=True)),
                ('etat_apres', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('attribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='assets.attribution')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique Attribution',
                'verbose_name_plural': 'Historiques Attribution',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(default='NEW', max_length=50)),
                ('numero_inventaire', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('modele', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('etat_technique', models.CharField(choices=[('FONCTIONNEL', 'Fonctionnel'), ('DEFECTUEUX', 'Défectueux'), ('EN_MAINTENANCE', 'En maintenance')], default='FONCTIONNEL', max_length=20)),
                ('statut_disponibilite', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ATTRIBUE', 'Attribué'), ('MAINTENANCE', 'Maintenance'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=20)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qr_code', models.FileField(blank=True, null=True, upload_to='qr_codes/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='assets.categorie')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='assets.departement')),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'ordering': ['-date_creation'],
                'unique_together': {('asset_id', 'departement')},
            },
        ),
        migrations.AddField(
            model_name='attribution',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='assets.materiel'),
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('RETARD', 'Retard de retour'), ('DEFECTUEUX', 'Matériel défectueux'), ('STOCK_CRITIQUE', 'Stock critique'), ('PERDU', 'Matériel perdu')], max_length=20)),
                ('severite', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('CRITICAL', 'Critique')], default='WARNING', max_length=20)),
                ('description', models.TextField()),
                ('reglementee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('attribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='assets.attribution')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='assets.departement')),
                ('materiel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='assets.materiel')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
