# Generated by Django 5.2.8 on 2025-11-23 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_client_type_client_salle_materiel_salle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='assets.salle'),
        ),
    ]
