# Generated by Django 5.2.8 on 2025-11-24 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='assets.salle'),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='assets.client'),
        ),
    ]
