# Generated by Django 5.2.8 on 2025-12-09 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_attribution_salle_alter_attribution_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('CREATION', 'Notification de création'), ('RAPPEL_2H', 'Rappel 2h avant'), ('RAPPEL_J_MOINS_2', 'Rappel J-2'), ('RAPPEL_J_MOINS_1', 'Rappel J-1'), ('RAPPEL_FINAL', 'Rappel jour retour'), ('RETARD', 'Alerte retard'), ('RESTITUTION', 'Confirmation restitution')], max_length=20)),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('duree_emprunt', models.CharField(help_text="Snapshot de la durée au moment de l'envoi", max_length=10)),
                ('destinataire', models.CharField(help_text='Email ou téléphone du destinataire', max_length=200)),
                ('statut', models.CharField(choices=[('ENVOYEE', 'Envoyée'), ('ECHEC', 'Échec (retry en cours)'), ('ECHEC_PERM', 'Échec définitif')], default='ENVOYEE', max_length=20)),
                ('message_id', models.CharField(blank=True, help_text='ID du message provider (Twilio, etc.)', max_length=255, null=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_scheduled', models.DateTimeField(blank=True, help_text="Quand était prévu l'envoi", null=True)),
                ('date_tentative_prochaine', models.DateTimeField(blank=True, help_text='Prochaine tentative de retry', null=True)),
                ('erreur_message', models.TextField(blank=True, null=True)),
                ('nb_tentatives', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_email', models.BooleanField(default=True, help_text='Recevoir les notifications par email')),
                ('notifications_whatsapp', models.BooleanField(default=False, help_text='Recevoir les notifications par WhatsApp')),
                ('rappel_j_moins_2', models.BooleanField(default=True, help_text='Rappel J-2')),
                ('rappel_j_moins_1', models.BooleanField(default=True, help_text='Rappel J-1')),
                ('rappel_final', models.BooleanField(default=True, help_text='Rappel jour de retour')),
                ('rappel_2h_avant', models.BooleanField(default=True, help_text='Rappel 2h avant pour moyen terme')),
                ('phone_number', models.CharField(blank=True, help_text='Numéro WhatsApp (+33612345678)', max_length=20, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Préferences Notification',
                'verbose_name_plural': 'Préferences Notifications',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_provider', models.CharField(choices=[('TWILIO', 'Twilio')], default='TWILIO', help_text='Fournisseur API pour WhatsApp', max_length=20)),
                ('api_key', models.CharField(help_text='Clé API (compte, SID, token, etc.)', max_length=255)),
                ('api_secret', models.CharField(blank=True, help_text="Secret API (token d'authentification)", max_length=255, null=True)),
                ('phone_number_sender', models.CharField(help_text='Numéro Twilio sender (+1234567890 ou lien sandbox)', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Configuration active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration WhatsApp',
                'verbose_name_plural': 'Configuration WhatsApp',
            },
        ),
        migrations.AddField(
            model_name='attribution',
            name='duree_emprunt',
            field=models.CharField(choices=[('COURT', 'Court terme (< 4h)'), ('MOYEN', 'Moyen terme (4h - 24h)'), ('LONG', 'Long terme (> 24h)')], default='LONG', help_text='Catégorie automatique basée sur la durée totale', max_length=10),
        ),
        migrations.AddField(
            model_name='attribution',
            name='heure_retour_effective',
            field=models.TimeField(blank=True, help_text='Heure effective de retour', null=True),
        ),
        migrations.AddField(
            model_name='attribution',
            name='heure_retour_prevue',
            field=models.TimeField(blank=True, help_text='Heure de retour prévue (pour emprunts < 24h)', null=True),
        ),
        migrations.AddIndex(
            model_name='attribution',
            index=models.Index(fields=['duree_emprunt', 'date_retour_effective'], name='assets_attr_duree_e_00718e_idx'),
        ),
        migrations.AddIndex(
            model_name='attribution',
            index=models.Index(fields=['date_retour_prevue', 'duree_emprunt'], name='assets_attr_date_re_59c8ef_idx'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='attribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='assets.attribution'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='assets.client'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['attribution', 'type_notification'], name='assets_noti_attribu_d84cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['statut', 'date_tentative_prochaine'], name='assets_noti_statut_29bbf0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['date_envoi'], name='assets_noti_date_en_7af5e1_idx'),
        ),
    ]
