# Generated by Django 5.2.9 on 2026-01-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_set_db_defaults'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materiel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='asset_id',
            field=models.CharField(default='NEW', max_length=50, unique=True),
        ),
    ]
