# Generated by Django 5.2 on 2026-01-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_make_asset_id_unique_globally'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='location',
            field=models.CharField(blank=True, help_text='Localisation physique du matériel (ex: Bureau IT, Salle 122, etc.)', max_length=200, null=True, verbose_name='Localisation'),
        ),
    ]
