# Generated by Codex
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_add_location_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='type_attribution',
            field=models.CharField(
                choices=[
                    ('TEMPORAIRE', 'Temporaire'),
                    ('INDEFINIE', 'Indéfinie (interne)'),
                    ('USAGE_UNIQUE', 'Usage unique'),
                ],
                default='TEMPORAIRE',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='date_retour_prevue',
            field=models.DateField(blank=True, null=True),
        ),
    ]
